In [1]:
import oceanbench

oceanbench.__version__

'0.0.3'

### Open challenger datasets

> Insert here the code that opens the challenger dataset as `challenger_dataset: xarray.Dataset`

In [2]:
import xarray as xr
import pathlib
import os

if (challenger_path := os.getenv("CHALLENGER_DATASET_PATH")) is None:
  raise ValueError("Please set the CHALLENGER_DATASET_PATH environment variable.")

challenger_path = pathlib.Path(challenger_path).resolve()
if not challenger_path.exists():
  raise ValueError(f"Path {challenger_path} does not exist.")

challenger_dataset: xr.Dataset = xr.open_dataset(challenger_path, engine='zarr', chunks={'lead_day_index': 1,
                                                                                         'first_day_datetime': 1})
challenger_dataset

/tmp/ipykernel_1608205/1546624352.py:12: UserWarning: The specified chunks separate the stored chunks along dimension "first_day_datetime" starting at index 1. This could degrade performance. Instead, consider rechunking after loading.
  challenger_dataset: xr.Dataset = xr.open_dataset(challenger_path, engine='zarr', chunks={'lead_day_index': 1,
/tmp/ipykernel_1608205/1546624352.py:12: UserWarning: The specified chunks separate the stored chunks along dimension "lead_day_index" starting at index 1. This could degrade performance. Instead, consider rechunking after loading.
  challenger_dataset: xr.Dataset = xr.open_dataset(challenger_path, engine='zarr', chunks={'lead_day_index': 1,

<xarray.Dataset> Size: 83GB
Dimensions:                          (depth: 10, first_day_datetime: 52,
                                      lead_day_index: 10, latitude: 672,
                                      longitude: 1440)
Coordinates:
  * depth                            (depth) float32 40B 0.494 5.078 ... 902.3
  * first_day_datetime               (first_day_datetime) datetime64[ns] 416B ...
  * latitude                         (latitude) float32 3kB -78.0 ... 89.75
  * lead_day_index                   (lead_day_index) int64 80B 0 1 2 ... 7 8 9
  * longitude                        (longitude) float32 6kB -179.8 ... 180.0
Data variables:
    eastward_sea_water_velocity      (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 20GB dask.array<chunksize=(1, 1, 2, 168, 360), meta=np.ndarray>
    northward_sea_water_velocity     (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 20GB dask.array<chunksize=(1, 1, 2, 168, 360), meta=np.ndarray>
    sea_surface_height_above_geoid   (first_day_datetime, lead_day_index, latitude, longitude) float32 2GB dask.array<chunksize=(1, 1, 168, 360), meta=np.ndarray>
    sea_water_potential_temperature  (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 20GB dask.array<chunksize=(1, 1, 2, 168, 360), meta=np.ndarray>
    sea_water_salinity               (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 20GB dask.array<chunksize=(1, 1, 2, 168, 360), meta=np.ndarray>
Attributes:
    Conventions:  CF-1.8
    area:         Global
    title:        OceanBench Challenge

### Evaluation of challenger dataset using OceanBench

#### Root Mean Square Deviation (RMSD) of variables compared to GLORYS reanalysis

In [3]:
oceanbench.metrics.rmsd_of_variables_compared_to_glorys_reanalysis(challenger_dataset)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Surface height,0.069248,0.071755,0.073514,0.075792,0.078648,0.081853,0.085274,0.089289,0.092923,0.096533
Surface temperature,0.612016,0.689689,0.739063,0.773307,0.805086,0.839763,0.877640,0.917932,0.958266,1.000779
Surface salinity,0.761527,0.698897,0.661766,0.643390,0.639103,0.646142,0.659708,0.676234,0.693915,0.710870
Surface northward velocity,0.117280,0.119319,0.121710,0.124381,0.127614,0.131040,0.134656,0.138343,0.141111,0.143804
Surface eastward velocity,0.118266,0.120604,0.123347,0.126545,0.130194,0.134197,0.138443,0.142780,0.146473,0.149933
50m temperature,0.820417,0.831689,0.842736,0.859001,0.881309,0.909372,0.942450,0.978963,1.015421,1.053884
50m salinity,0.396478,0.359647,0.334444,0.319133,0.311947,0.311000,0.314224,0.319910,0.326809,0.334466
50m northward velocity,0.111240,0.112489,0.114365,0.116912,0.119990,0.123394,0.126965,0.130493,0.133372,0.136072
50m eastward velocity,0.112069,0.113408,0.115488,0.118246,0.121520,0.125112,0.128934,0.132836,0.136131,0.139343
100m temperature,1.066964,1.060963,1.058963,1.061519,1.069558,1.084430,1.106055,1.132068,1.159508,1.190579
100m salinity,0.305148,0.280531,0.263529,0.253286,0.248346,0.247339,0.249128,0.252613,0.256978,0.262080
100m northward velocity,0.109353,0.109834,0.110939,0.112867,0.115331,0.118129,0.121205,0.124353,0.126853,0.129220
100m eastward velocity,0.112863,0.113496,0.114829,0.116892,0.119485,0.122343,0.125451,0.128668,0.131312,0.133858
200m temperature,2.260169,2.240993,2.220445,2.200821,2.182482,2.166746,2.154237,2.144604,2.136848,2.131718
200m salinity,0.334140,0.321459,0.311059,0.303049,0.297063,0.292674,0.289569,0.287458,0.286013,0.285242
200m northward velocity,0.106272,0.105452,0.105516,0.106265,0.107453,0.109013,0.110968,0.113062,0.114777,0.116496
200m eastward velocity,0.112811,0.112433,0.112856,0.113729,0.114897,0.116358,0.118072,0.119934,0.121493,0.123072
300m temperature,0.706004,0.705789,0.708621,0.714803,0.724252,0.736957,0.752605,0.770355,0.787717,0.806300
300m salinity,0.123395,0.123011,0.123658,0.124843,0.126557,0.128794,0.131520,0.134625,0.137837,0.141350
300m northward velocity,0.102146,0.101306,0.101155,0.101553,0.102341,0.103484,0.104972,0.106579,0.107868,0.109191
300m eastward velocity,0.105397,0.104579,0.104516,0.104964,0.105754,0.106868,0.108282,0.109868,0.111235,0.112619
500m temperature,1.166300,1.168084,1.171794,1.177492,1.184930,1.194004,1.204559,1.216231,1.228215,1.241161
500m salinity,0.140910,0.154360,0.160158,0.162114,0.163001,0.163544,0.164032,0.164548,0.165036,0.165630
500m northward velocity,0.091616,0.090427,0.089873,0.089821,0.090185,0.090872,0.091839,0.092946,0.093858,0.094800
500m eastward velocity,0.094761,0.093749,0.093405,0.093523,0.094004,0.094785,0.095805,0.096957,0.097967,0.098994

#### Root Mean Square Deviation (RMSD) of Mixed Layer Depth (MLD) compared to GLORYS reanalysis

In [4]:
oceanbench.metrics.rmsd_of_mixed_layer_depth_compared_to_glorys_reanalysis(challenger_dataset)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Mixed layer depth,54.521694,58.009609,60.960403,63.753193,66.262787,68.652405,71.077202,73.323105,75.384834,77.205818

#### Root Mean Square Deviation (RMSD) of geostrophic currents compared to GLORYS reanalysis

In [5]:
oceanbench.metrics.rmsd_of_geostrophic_currents_compared_to_glorys_reanalysis(challenger_dataset)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Northward geostrophic velocity,0.150391,0.189123,0.200714,0.206056,0.210805,0.215836,0.221450,0.227499,0.233421,0.239858
Eastward geostrophic velocity,0.154303,0.188032,0.197094,0.201411,0.205102,0.209603,0.214454,0.219441,0.224808,0.230724

#### Deviation of Lagrangian trajectories compared to GLORYS reanalysis

In [6]:
oceanbench.metrics.deviation_of_lagrangian_trajectories_compared_to_glorys_reanalysis(challenger_dataset)

,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9
Surface Lagrangian trajectory deviation (km),9.49708,18.155293,26.325569,34.213215,41.923359,49.514996,57.046589,64.521492

#### Root Mean Square Deviation (RMSD) of variables compared to GLO12 analysis

In [7]:
oceanbench.metrics.rmsd_of_variables_compared_to_glo12_analysis(challenger_dataset)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Surface height,0.022465,0.034390,0.042134,0.048985,0.055536,0.061669,0.067579,0.073340,0.078015,0.082617
Surface temperature,0.327552,0.480301,0.569176,0.628609,0.678446,0.726184,0.774406,0.823095,0.868061,0.913769
Surface salinity,0.253507,0.412087,0.518803,0.604036,0.676403,0.740061,0.797201,0.846723,0.887759,0.921574
Surface northward velocity,0.057772,0.080738,0.095366,0.106691,0.116530,0.124806,0.132195,0.138769,0.143298,0.147192
Surface eastward velocity,0.057083,0.080141,0.095299,0.107397,0.117708,0.126656,0.134833,0.142293,0.147913,0.152639
50m temperature,0.564421,0.627390,0.676907,0.722125,0.768157,0.814925,0.863252,0.911070,0.952534,0.994090
50m salinity,0.119409,0.159616,0.201429,0.239870,0.274121,0.304470,0.330934,0.354168,0.373780,0.390678
50m northward velocity,0.047940,0.068189,0.083338,0.095419,0.105723,0.114593,0.122396,0.129227,0.134169,0.138392
50m eastward velocity,0.049342,0.068667,0.083500,0.095504,0.105918,0.115136,0.123378,0.130655,0.136118,0.140780
100m temperature,0.920918,0.939521,0.958897,0.979911,1.003330,1.030044,1.060479,1.093285,1.122095,1.153000
100m salinity,0.139223,0.142447,0.156476,0.173973,0.191920,0.209189,0.225195,0.239637,0.251989,0.263038
100m northward velocity,0.045641,0.062752,0.076937,0.088815,0.099050,0.107910,0.115741,0.122451,0.127297,0.131363
100m eastward velocity,0.052194,0.067239,0.080495,0.091901,0.101880,0.110616,0.118424,0.125317,0.130582,0.134958
200m temperature,2.341866,2.329296,2.316555,2.304756,2.293758,2.284467,2.277852,2.273086,2.268312,2.265194
200m salinity,0.322591,0.311866,0.303649,0.297770,0.293732,0.291052,0.289450,0.288585,0.287991,0.287832
200m northward velocity,0.048604,0.058310,0.069219,0.079382,0.088404,0.096406,0.103646,0.109987,0.114677,0.118685
200m eastward velocity,0.062381,0.069705,0.078552,0.087060,0.094864,0.101951,0.108356,0.114030,0.118396,0.122150
300m temperature,0.127529,0.221882,0.304641,0.375754,0.438070,0.494242,0.546194,0.593245,0.631467,0.666730
300m salinity,0.021309,0.038849,0.054126,0.066815,0.077553,0.086958,0.095456,0.103122,0.109621,0.115723
300m northward velocity,0.026792,0.044420,0.058361,0.069671,0.079172,0.087332,0.094530,0.100752,0.105361,0.109321
300m eastward velocity,0.026458,0.042580,0.055955,0.066918,0.076192,0.084223,0.091304,0.097490,0.102216,0.106282
500m temperature,0.948013,0.957005,0.969782,0.985200,1.002394,1.020843,1.040309,1.060004,1.077959,1.096043
500m salinity,0.124273,0.149091,0.161287,0.166286,0.169036,0.170836,0.172223,0.173378,0.174220,0.175046
500m northward velocity,0.034001,0.043421,0.052945,0.061537,0.069130,0.075872,0.081938,0.087240,0.091237,0.094698
500m eastward velocity,0.034971,0.043117,0.051905,0.060053,0.067324,0.073821,0.079672,0.084866,0.088880,0.092385

#### Root Mean Square Deviation (RMSD) of Mixed Layer Depth (MLD) compared to GLO12 analysis

In [8]:
oceanbench.metrics.rmsd_of_mixed_layer_depth_compared_to_glo12_analysis(challenger_dataset)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Mixed layer depth,45.343182,51.696255,56.803238,60.910175,64.462387,67.550468,70.443657,72.944473,75.203949,77.341736

#### Root Mean Square Deviation (RMSD) of geostrophic currents compared to GLO12 analysis

In [9]:
oceanbench.metrics.rmsd_of_geostrophic_currents_compared_to_glo12_analysis(challenger_dataset)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Northward geostrophic velocity,0.114861,0.167849,0.183932,0.192954,0.200879,0.208653,0.216674,0.22451,0.231572,0.238488
Eastward geostrophic velocity,0.123628,0.172185,0.184106,0.191165,0.197761,0.204687,0.212118,0.21895,0.225158,0.231816

#### Deviation of Lagrangian trajectories compared to GLO12 analysis

In [10]:
oceanbench.metrics.deviation_of_lagrangian_trajectories_compared_to_glo12_analysis(challenger_dataset)

,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9
Surface Lagrangian trajectory deviation (km),4.789611,10.118022,15.920948,22.298594,29.1768,36.445465,44.026199,51.798306